[project]
name = "ggs-accounting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "PyQt6",
    "pytest",
    "pydantic",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["data"]
